#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CONTRACTS_DIR="$( dirname "${SCRIPT_DIR}" )"
REPO_ROOT="$( cd "${CONTRACTS_DIR}/../.." && pwd )"
API_DIR="${REPO_ROOT}/services/api"
API_GENERATED="${API_DIR}/app/generated"
OPENAPI_SPEC="${CONTRACTS_DIR}/openapi.yaml"

mkdir -p "${API_GENERATED}"
touch "${API_GENERATED}/__init__.py"

(cd "${API_DIR}" && uv run datamodel-codegen \
  --input "${OPENAPI_SPEC}" \
  --input-file-type openapi \
  --output "${API_GENERATED}/models.py" \
  --output-model-type pydantic_v2.BaseModel \
  --target-python-version 3.12 \
  --use-schema-description \
  --disable-timestamp \
  --field-constraints \
  --snake-case-field \
  --use-field-description)

(cd "${API_DIR}" && uv run fastapi-codegen \
  --input "${OPENAPI_SPEC}" \
  --output "${API_GENERATED}/_fastapi_out" \
  --model-file "models" \
  --disable-timestamp)

cp "${API_GENERATED}/_fastapi_out/main.py" "${API_GENERATED}/routes.py"
rm -rf "${API_GENERATED}/_fastapi_out"

for f in "${API_GENERATED}/models.py" "${API_GENERATED}/routes.py"; do
  { echo "# AUTO-GENERATED by packages/contracts/scripts/generate-python.sh"; \
    echo "# DO NOT EDIT BY HAND. Regenerate with \`pnpm -C packages/contracts generate:py\`."; \
    echo ""; \
    cat "${f}"; } > "${f}.new"
  mv "${f}.new" "${f}"
done

echo "Generated: ${API_GENERATED}/models.py"
echo "Generated: ${API_GENERATED}/routes.py"
