#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CONTRACTS_DIR="$( dirname "${SCRIPT_DIR}" )"
REPO_ROOT="$( cd "${CONTRACTS_DIR}/../.." && pwd )"
SDK_GENERATED="${REPO_ROOT}/packages/sdk/src/generated"
OPENAPI_SPEC="${CONTRACTS_DIR}/openapi.yaml"

mkdir -p "${SDK_GENERATED}"

pnpm exec openapi-typescript "${OPENAPI_SPEC}" \
  --output "${SDK_GENERATED}/api-types.ts"

cat > "${SDK_GENERATED}/api-client.ts" <<'INNEREOF'
// AUTO-GENERATED by packages/contracts/scripts/generate-typescript.sh
// DO NOT EDIT BY HAND. Regenerate with `pnpm -C packages/contracts generate:ts`.
import createClient from "openapi-fetch";
import type { paths } from "./api-types.js";

export type ApiPaths = paths;

export interface ApiClientOptions {
  baseUrl: string;
}

export function createApiClient(opts: ApiClientOptions) {
  return createClient<paths>({ baseUrl: opts.baseUrl });
}
INNEREOF

echo "Generated: ${SDK_GENERATED}/api-types.ts"
echo "Generated: ${SDK_GENERATED}/api-client.ts"
