// @vitest-environment jsdom
/// <reference types="node" />
//
// One statement says where the demo catalog comes from, and every surface repeats
// it verbatim. The storefront footer once credited a Kaggle dataset under MIT while
// NOTICE credited the McAuley Lab's Amazon Reviews 2023 — and neither was the file
// the catalog was actually built from. Now the catalog is generated by this repo,
// the statement lives in catalog-attribution.json, and these tests fail the moment
// the footer, NOTICE, README or docs say anything else.

import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { cleanup, render, screen } from "@testing-library/react";
import { afterEach, describe, expect, it } from "vitest";
import attribution from "./catalog-attribution.json";
import { Footer } from "./components/Footer";

afterEach(cleanup);

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "../../..");
const read = (path: string) => readFileSync(join(repoRoot, path), "utf8");

/** Every public surface that describes the demo data. */
const SURFACES = [
	"NOTICE",
	"README.md",
	"docs/USAGE.md",
	"docs/QUICKSTART.md",
	"frontend/app/src/locales/en/common.json",
];

/** Credits for the data the catalog no longer contains. */
const STALE_CREDITS =
	/kaggle|mcauley|amazon reviews|amazon-reviews-2023|amazon e-commerce/i;

describe("catalog attribution has one source of truth", () => {
	it("pins the statement: synthetic, generated here, MIT", () => {
		expect(attribution.statement).toBe(
			"Synthetic demo catalog generated by backend/scripts/generate_catalog.py (MIT). Every brand and product in it is invented.",
		);
		expect(attribution.license).toBe("MIT");
	});

	it("names a generator that exists in the repo", () => {
		expect(existsSync(join(repoRoot, attribution.generator))).toBe(true);
	});

	it("the storefront footer shows the statement", () => {
		render(<Footer />);
		expect(
			screen.getByText(`Product data: ${attribution.statement}`),
		).toBeInTheDocument();
	});

	it.each(["NOTICE", "README.md"])(
		"%s carries the statement verbatim",
		(path) => {
			expect(read(path)).toContain(attribution.statement);
		},
	);

	it.each(SURFACES)(
		"%s credits no dataset the catalog is not built from",
		(path) => {
			expect(read(path)).not.toMatch(STALE_CREDITS);
		},
	);
});
