name: Dagger
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  dagger:
    name: Dagger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: dagger/dagger-for-github@27b130bf0f79a7f6fbbbe0fbca6760dc9bb40a77 # v8.4.1
        with:
          version: "0.21.8"
          verb: check
  sarif:
    name: Dagger SARIF
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: dagger/dagger-for-github@27b130bf0f79a7f6fbbbe0fbca6760dc9bb40a77 # v8.4.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          version: "0.21.8"
          call: >-
            codeql-upload
            --github-token=env:GITHUB_TOKEN
            --commit-sha=${{ github.sha }}
            --ref=${{ github.ref }}
            --repository=${{ github.repository }}
